name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Change this line in your YAML if your GitHub secret is named 'review'
        run: git push --force https://greesh2:${{ secrets.review }}@huggingface.co/spaces/greesh2/Reviewsys main
